IPL_Site/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from iplapp.views import home, register_view, login_view, logout_view

urlpatterns = [
    re_path(r'^accounts/login/$', login_view, name='login'),
    re_path(r'^accounts/logout/$', logout_view, name='logout'),
    path('admin/', admin.site.urls),
    path('iplapp/', include('iplapp.urls', namespace='iplapp')),
    path('', home, name='home'),
    re_path(r'^home/$', home, name='home'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', register_view, name='register'),
]

iplapp/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.views.static import serve
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'iplapp'

urlpatterns = [

    path('', views.home, name="home"),
    re_path(r'^home/$', views.home, name='home'),

    path('register/success/', views.register_success, name='success'),
    path('password/', views.change_password, name='change_password'),
    path('password/success/', views.password_success, name='password_success'),
    # team views
    path('team_list', views.team_list, name='team_list'),
    path('team/<int:pk>/', views.team_detail, name='team_detail'),
    path('team/new/', views.team_new, name='team_new'),
    path('team/<int:pk>/edit/', views.team_edit, name='team_edit'),
    path('team/<int:pk>/delete/', views.team_delete, name='team_delete'),

    #### Matches

    path('point_table_refresh', views.refresh_point_table, name='refresh_point_table'),

    # path('match_list', views.match_list, name='match_list'),
    path('match_list/<int:pk>', views.match_list, name='match_list'),
    path('referee/<int:pk>', views.match_referee, name='match_referee'),
    path('match/<int:pk>/', views.match_detail, name='match_detail'),
    path('match/<int:pk>/edit', views.match_edit, name='match_edit'),
    path('match/new', views.match_new, name='match_new'),
    path('match/<int:pk>/delete/', views.match_delete, name='match_delete'),

    #Player views
    path('player/<int:pk>/', views.player_detail, name='player_detail'),
    path('player_list', views.player_list, name='player_list'),
    path('player_list/<int:pk>', views.myteamplayer_list, name='myteamplayer_list'),
    path('player/<int:coachid>/new/', views.player_new, name='player_new'),
    path('player/<int:pk>/<int:coachid>/edit/', views.player_edit, name='player_edit'),
    path('player/<int:pk>/<int:coachid>/delete/', views.player_delete, name='player_delete'),

    #Roles views
    path('assign_role', views.assign_role, name='assign_role'),
    path('roles', views.role_list, name='role_list'),
    path('roles/delete/<int:pk>/', views.delete_role, name='delete_role'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
            serve, {'document_root': settings.MEDIA_ROOT,})
    ]

iplapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Team, Player, Match, IPLrole, PlayerStats
from .forms import TeamForm, PlayerFormEditAdd, MatchForm, PlayerStatsForm, MatchStatusForm, AssignRoleForm
from .forms import UserLoginForm, UserRegisterForm, PlayerForm, User, authenticate, login, logout
from django.utils import timezone
from django.db.models import Count, Sum
from django.db.models import Q, F
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.core.mail import send_mail
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect



# Create your views here.
###### Team Views ######

def team_list(request):
    teams = Team.objects.filter(active_status='active')
    return render(request, 'iplapp/team/team_list.html', {'teams': teams})


def team_detail(request, pk):
    cap = 'None';
    Won = 0;
    Lost = 0;
    Drawn = 0;
    try:
        team = get_object_or_404(Team, pk=pk)
        name = team.team_name
        run_list = PlayerStats.objects.filter(team=team).order_by('-created_date')[:10]
        matchesasguest = Match.objects.filter(guest_team=team.id)
        for match in matchesasguest:
            if match.guest_team_score > match.home_team_score:
                Won = Won + 1;
            if match.guest_team_score == match.home_team_score:
                Drawn = Drawn + 1
            if match.guest_team_score < match.home_team_score:
                Lost = Lost + 1

        matchesashome = Match.objects.filter(home_team=team.id)
        for match in matchesashome:
            if match.home_team_score > match.guest_team_score:
                Won = Won + 1;
            if match.guest_team_score == match.home_team_score:
                Drawn = Drawn + 1
            if match.home_team_score < match.guest_team_score:
                Lost = Lost + 1
        players = Player.objects.filter(team=team.id).filter(eligibility_status='eligible')
        for player in players:
            if player.team_role == 'captain':
                cap = player.first_name + " " + player.last_name
        totalrun = run_list.aggregate(TOTAL=Sum('run'))['TOTAL']
        return render(request, 'iplapp/team/team_detail.html', {'team': team,
                                                'run_list': run_list,
                                                'goals_count': totalrun,'players':players,
                                                'cap':cap,'Won':Won,'Lost':Lost,'Drawn':Drawn
                                                      })
    except Team.DoesNotExist:
        return render(request, 'iplapp/team/team_detail.html',
                      {'run_list': None,'cap':None,'players':None,'totalrun':0})

@login_required
def team_new(request):
    if request.method == "POST":
        #update
        form = TeamForm(request.POST)
        if form.is_valid():
            team = form.save(commit=False)
            team.created_date = timezone.now()
            team.save()
            teams = Team.objects.filter(created_date__lte=timezone.now())
            return render(request, 'iplapp/team/team_list.html', {'teams': teams})
    else:
        #edit
        form = TeamForm()
    return render(request, 'iplapp/team/team_edit.html', {'form': form})

@login_required
def team_edit(request, pk):
    team = get_object_or_404(Team, pk=pk)
    if request.method == "POST":
        form = TeamForm(request.POST, instance=team)
        if form.is_valid():
            team = form.save(commit=False)
            team.created_date = timezone.now()
            team.save()
            teams = Team.objects.filter(created_date__lte=timezone.now())
            return render(request, 'iplapp/team/team_list.html', {'teams': teams})
    else:
        #edit
        form = TeamForm(instance=team)
    return render(request, 'iplapp/team/team_edit.html', {'form': form})

@login_required
def team_delete(request, pk):
    team = get_object_or_404(Team, pk=pk)
    team.active_status = 'inactive'
    team.save()
    return redirect('iplapp:team_list')


## Player Views
def player_detail(request, pk):
    player = get_object_or_404(Player, pk=pk)
    team = player.team
    run_list = PlayerStats.objects.filter(player=player).order_by('-created_date')[:5]
    run_count = run_list.aggregate(TOTAL=Sum('run'))['TOTAL']
    return render(request, 'iplapp/player/player_detail.html', {'player': player,
                                                                'run_list': run_list,
                                                                'run_count': run_count,
                                                                'team': team})


def player_list(request):
    player_list = Player.objects.exclude(eligibility_status='ineligible')
    player_count = player_list.count()

    if(request.method == "GET"):
        qs = request.GET.get('playername')
        if qs:
            player_list = Player.objects.filter(Q(last_name__icontains=qs) |
                                                Q(first_name__icontains=qs)).exclude(eligibility_status='ineligible')
    return render(request, 'iplapp/player/player_list.html', {'player_list': player_list,
                                                              'player_count': player_count})

@login_required
def myteamplayer_list(request, pk):
    try:
        team = Team.objects.get(coach_id=pk)
        if team != None:
            myPlayer = Player.objects.filter(team=team.id)
            player_count = myPlayer.count()
        return render(request, 'iplapp/player//myteamplayer_list.html',
                      {'myplayer': myPlayer,
                       'player_count': player_count,
                       'coachid': pk})
    except Team.DoesNotExist:
        return render(request, 'iplapp/player/myteamplayer_list.html',
                      {'myplayer': None,
                       'player_count': 0,
                       'coachid': pk
                       })

@login_required
def player_new(request, coachid):
    if request.method == 'POST':
        form = PlayerFormEditAdd(request.POST)
        if form.is_valid():
            try:
                team = Team.objects.get(coach_id=coachid)
                if team != None:
                    player = form.save(commit=False)
                    player.created_date = timezone.now()
                    player.team = team
                    player.save()

                    players = Player.objects.filter(team=team.id)
                    player_count = players.count()
                return render(request, 'iplapp/player/myteamplayer_list.html',
                              {'myplayer': players,
                               'player_count': player_count,
                               'coachid': coachid})
            except Team.DoesNotExist:
                return render(request, 'iplapp/player/myteamplayer_list.html',
                              {'myplayer': None,
                               'player_count': 0,
                               'coachid': coachid
                               })
    else:
        #edit player
        form = PlayerFormEditAdd()
    return render(request, 'iplapp/player/player_edit.html', {'form': form})

@login_required
def player_edit(request, pk, coachid):
    player = get_object_or_404(Player, pk=pk)
    if request.method == "POST":
        #update
        form = PlayerFormEditAdd(request.POST, instance=player)
        if form.is_valid():
            team = Team.objects.get(coach_id=coachid)
            if team != None:
                player = form.save(commit=False)
                player.updated_date = timezone.now()
                player.team = team
                player.save()

                players = Player.objects.filter(team=team.id)
                player_count = players.count()
            #players = Player.objects.filter(created_date__lte=timezone.now())
            return render(request, 'iplapp/player/myteamplayer_list.html',
                          {'myplayer': players,
                           'player_count': player_count,
                           'coachid': coachid})
    else:
        # edit
        form = PlayerFormEditAdd(instance = player)
    return render(request, 'iplapp/player/player_edit.html', {'form': form})

@login_required
def player_delete(request, pk, coachid):
    player = get_object_or_404(Player, pk=pk)
    player.eligibility_status = 'ineligible'
    player.save()
    team = Team.objects.get(coach_id=coachid)
    if team != None:
        players = Player.objects.filter(team=team.id)
        player_count = players.count()
    return render(request, 'iplapp/player/myteamplayer_list.html',
                            {'myplayer': players,
                            'player_count': player_count,
                             'coachid': coachid})

##### Homepage Views
##############################
def home(request):
    matches_sch = Match.objects.filter(match_status='scheduled').order_by('match_day', 'match_start_time')[:3]
    matches_full = Match.objects.filter(match_status='full_time').order_by('-match_day', '-match_start_time')[:3]
    matches_live = Match.objects.filter(match_status='in_progress')
    team_live = Team.objects.filter(id=1)
    player_run_scorer = PlayerStats.objects.values('player__first_name', 'player__last_name',
                                                  'player__team__team_short_name', 'player__team__team_logo_url')\
                                                .annotate(total_run=Sum('run'))\
                                                .order_by('-total_run')[:5]
    teams = Team.objects.filter(created_date__lte=timezone.now()).order_by('-team_point')
    return render(request, 'home.html', {'matches_sch': matches_sch,

iplapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IPL</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>
<body>
<!--Navigation Bar-->
<nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'iplapp:home' %}"><img width="100px" src="{% static 'ipl_images/media/IPL_logo.jpg' %}"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            {% with url_name=request.resolver_match.url_name %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if url_name == 'home' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'iplapp:home' %}">Home</a>
                </li>
                <li class="nav-item {% if url_name == 'match_list' %}active{% endif %}">
                {#<a class="nav-link" href="{% url 'iplapp:match_list' %}">Matches</a>#}
                    <a class="nav-link" href="{% url 'iplapp:match_list' pk=1%}">Matches</a>
                </li>
                <li class="nav-item {% if url_name == 'team_list' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'iplapp:team_list' %}">Teams</a>
                </li>
                <li class="nav-item {% if url_name == 'player_list' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'iplapp:player_list' %}">Players</a>
                </li>
                 {% if user.is_authenticated and request.user.is_superuser or user.groups.all and user.groups.all.0.name == "Admin" %}
                    <li class="nav-item {% if url_name == 'role_list' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'iplapp:role_list' %}">Roles</a>
                    </li>
                {% endif %}
                {% if user.is_authenticated and user.groups.all and user.groups.all.0.name == "Coach" %}
                <li class="nav-item {% if url_name == 'myteamplayer_list' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'iplapp:myteamplayer_list' pk=user.pk %}" >My Team</a>
                </li>
                {% endif %}
                {% if user.is_authenticated and user.groups.all and user.groups.all.0.name == "Scorer" %}
                <li class="nav-item {% if url_name == 'match_referee' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'iplapp:match_referee' pk=user.pk %}" >My Matches</a>
                </li>
                {% endif %}
            </ul>
            {% endwith %}
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.first_name }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'iplapp:change_password' %}">Change Password</a>
                            <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

iplapp/templates/base_register.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title%} {% endblock%}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="{% static "css/style.css" %}" rel="stylesheet">
    </head>
    <body background="yellow">

        <div id="sidebar">
            <h2> IPL WebSite</h2>
        </div>
        <!--Navigation Bar-->
        <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'iplapp:home' %}"><img width="200px" src="{% static 'ipl_images/media/IPL_logo.jpg' %}"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    {{ user.first_name }}
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="{% url 'iplapp:change_password' %}">Change Password</a>
                                    <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                                </div>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'register' %}">Register</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
<br/>
        <div style="margin-left:10%" align=center>
            <div class='col-sm-8 col-sm-offset-3'>

              {% block body %}
              {% endblock %}
            </div>
        </div>
    </body>
</html>

iplapp/templates/home.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

{% if matches_live %}
<div class="container">
<div class="row text-center">
<div class="ipl-scorecard col-12 mx-0 pt-0">
    <div id="carouselLive" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            {% for match in matches_live %}
            <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
                    <div class="row text-left mt-2 pl-1">
                        <div class="col-12">
                            <h6>
                                {{match.match_day}} | {{match.field}} | Started at {{match.match_start_time}}
                                &nbsp;<span class="ipl-status-box">LIVE</span>
                            </h6>
                            <hr>
                        </div>
                    </div>
                    <div class="row mx-1">
                        <div class="col-4 col-sm-4 col-md-4 col-lg-4">
                            <img src="{{ match.home_team.team_logo_url }}" class="img-fluid mx-auto mb-3" width="125">
                            <h3>{{match.home_team.team_name}}</h3>
                        </div>
                        <div class="col-4 col-sm-4 col-md-4 col-lg-4 my-auto">
                            <span class="ipl-livescore">
                                {{match.home_team_score}} - {{match.guest_team_score}}
                            </span>
                            <p class="ipl-livescore-sub">
                            {% if match.match_status == 'scheduled' %}
                                Scheduled
                            {% elif match.match_status == 'in_progress'%}
                                In Progress
                            {% elif match.match_status == 'full_time'%}
                                Full Time
                            {% elif match.match_status == 'cancelled'%}
                                Cancelled
                            {% elif match.match_status == 'abandoned'%}
                                Abandoned
                            {% else %}
                                Status - Not Available
                            {% endif %}

                            </p>
                        </div>
                        <div class="col-4 col-sm-4 col-md-4 col-lg-4">
                            <img src="{{ match.guest_team.team_logo_url }}" class="img-fluid mx-auto mb-3" width="125">
                            <h3>{{match.guest_team.team_name}}</h3>
                        </div>
                    </div>
            </div>
            {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselLive" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselLive" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
</div>
</div>
{% endif %}
<div class="container">
<div class="row mb-4">
    <div class="ipl-card-dark col-md-6">
        <h3>Match Results</h3>
        <hr style="border-color: #d3d3d3;">
        <div class="ipl-list pt-2">
            {% for match in matches_full %}
                {% if forloop.counter != 1 %}
                    <hr style="border-color: #222; margin-top:0px; margin-bottom: 0px">
                {% endif %}
                <div class="row">
                    <div class="col-12 px-4 py-2" style="color: #8ebbec">
                        {{ match.match_day }}
                    </div>
                </div>
                <div class="row text-center">
                    <div class="col-4 py-0">
                        {{ match.home_team.team_short_name}}&nbsp;
                        <img src="{{ match.home_team.team_logo_url }}" class="img-fluid mx-auto mb-3" width="30">
                    </div>
                    <div class="col-4 py-0">
                        <span class="ipl-livescore-small">
                                {{match.home_team_score}} - {{match.guest_team_score}}
                        </span>
                    </div>
                    <div class="col-4 py-0">
                        <img src="{{ match.guest_team.team_logo_url }}" class="img-fluid mx-auto mb-3" width="30">
                        &nbsp;{{ match.guest_team.team_short_name}}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="ipl-card-dark col-md-6">
        <h3>Upcoming Matches</h3>
        <hr style="border-color: #d3d3d3;">
        <div class="ipl-list pt-2">
            {% for match in matches_sch %}
                {% if forloop.counter != 1 %}
                    <hr style="border-color: #222; margin-top:0px; margin-bottom: 0px">
                {% endif %}
                <div class="row">
                    <div class="col-12 px-4 py-2" style="color: #8ebbec">
                        {{ match.match_day }}
                    </div>
                </div>
                <div class="row text-center">
                    <div class="col-4 py-0">
                        {{ match.home_team.team_short_name}}&nbsp;
                        <img src="{{ match.home_team.team_logo_url }}" class="img-fluid mx-auto mb-3" width="30">

                    </div>
                    <div class="col-4 py-0">
                        vs
                    </div>
                    <div class="col-4 py-0">
                        <img src="{{ match.guest_team.team_logo_url }}" class="img-fluid mx-auto mb-3" width="30">
                        &nbsp;{{ match.guest_team.team_short_name}}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <h2>Season Statistics</h2>
    </div>
    <div class="ipl-card-light col-md-6">
        <h3>
            Point Table
            {% if user.is_authenticated and request.user.is_superuser or user.groups.all and user.groups.all.0.name == "Admin" %}
            <a class="btn btn-info" href="{% url 'iplapp:refresh_point_table' %}" data-toggle="tooltip" title="Refresh Points">
                <i class="fas fa-sync-alt"></i>
            </a>
            {% endif %}
        </h3>
        <hr style="border-color: #fff;">
        <table class="table table-hover">
        <thead class="thead-light">
        <tr>
            <th> Position </th>
            <th>Team Name </th>
            <th>Points</th>
        </tr>
        </thead>
        <tbody>
        {% for team in teams %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>  &nbsp; {{ team.team_short_name }}  </td>
            <td>{{ team.team_point }}</td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
    </div>
    <div class="ipl-card-light col-md-6">
        <h3>Top Scorers</h3>
        <hr style="border-color: #fff;">
        {% for player in player_run_scorer %}
                <div class="row">
                    <div class="col-3 text-right">
                        <img src="{{ player.player__team__team_logo_url }}" class="img-fluid mx-auto mb-3" width="50">
                    </div>
                    <div class="col-6">
                        <h4>
                            {{ player.player__first_name }}&nbsp;{{ player.player__last_name }}<br>
                            <small style="color:#ffc4c5">{{ player.player__team__team_short_name }}</small>
                        </h4>
                    </div>
                    <div class="col-3">
                        <h4>{{ player.total_run }}</h4>
                    </div>
                </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}

iplapp/templates/match_list_base.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="nav-scroller bg-white shadow-sm">
        <nav class="nav nav-underline">
        {% with url_name=request.resolver_match.url_name %}
            <a class="nav-link {% if url_name == 'match_list' and list_type == 'all' %}active{% endif %}" href="{% url 'iplapp:match_list' pk=1%}">All Matches</a>
            <a class="nav-link {% if url_name == 'match_list' and list_type == 'in_progress' %}active{% endif %}" href="{% url 'iplapp:match_list' pk=2%}">Live</a>
            <a class="nav-link {% if url_name == 'match_list' and list_type == 'finished' %}active{% endif %}" href="{% url 'iplapp:match_list' pk=3%}">Results</a>
            <a class="nav-link {% if url_name == 'match_list' and list_type == 'scheduled' %}active{% endif %}" href="{% url 'iplapp:match_list' pk=4%}">Upcoming</a>
            {% if user.is_authenticated and request.user.is_superuser or user.groups.all and user.groups.all.0.name == "Admin" %}
            <a class="btn btn-info" href="{% url 'iplapp:match_new' %}" data-toggle="tooltip" title="Add a Match">
                <i class="fas fa-plus" style="font-size: 1.2em; margin: 0rem; color: #FFFFFF; text-decoration: none;"></i>
            </a>
            {% endif %}
        {% endwith %}
        </nav>
    </div>
    {% block match_list_content %}
    {% endblock %}
{% endblock%}