IPL_Site/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from iplapp.views import home, register_view, login_view, logout_view

urlpatterns = [
    re_path(r'^accounts/login/$', login_view, name='login'),
    re_path(r'^accounts/logout/$', logout_view, name='logout'),
    path('admin/', admin.site.urls),
    path('iplapp/', include('iplapp.urls', namespace='iplapp')),
    path('', home, name='home'),
    re_path(r'^home/$', home, name='home'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', register_view, name='register'),
]

iplapp/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.views.static import serve
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'iplapp'

urlpatterns = [

    path('', views.home, name="home"),
    re_path(r'^home/$', views.home, name='home'),

    path('register/success/', views.register_success, name='success'),
    path('password/', views.change_password, name='change_password'),
    path('password/success/', views.password_success, name='password_success'),
    # team views
    path('team_list', views.team_list, name='team_list'),
    path('team/<int:pk>/', views.team_detail, name='team_detail'),
    path('team/new/', views.team_new, name='team_new'),
    path('team/<int:pk>/edit/', views.team_edit, name='team_edit'),
    path('team/<int:pk>/delete/', views.team_delete, name='team_delete'),

    #### Matches

    path('point_table_refresh', views.refresh_point_table, name='refresh_point_table'),

    # path('match_list', views.match_list, name='match_list'),
    path('match_list/<int:pk>', views.match_list, name='match_list'),
    path('referee/<int:pk>', views.match_referee, name='match_referee'),
    path('match/<int:pk>/', views.match_detail, name='match_detail'),
    path('match/<int:pk>/edit', views.match_edit, name='match_edit'),
    path('match/new', views.match_new, name='match_new'),
    path('match/<int:pk>/delete/', views.match_delete, name='match_delete'),

    #Player views
    path('player/<int:pk>/', views.player_detail, name='player_detail'),
    path('player_list', views.player_list, name='player_list'),
    path('player_list/<int:pk>', views.myteamplayer_list, name='myteamplayer_list'),
    path('player/<int:coachid>/new/', views.player_new, name='player_new'),
    path('player/<int:pk>/<int:coachid>/edit/', views.player_edit, name='player_edit'),
    path('player/<int:pk>/<int:coachid>/delete/', views.player_delete, name='player_delete'),

    #Roles views
    path('assign_role', views.assign_role, name='assign_role'),
    path('roles', views.role_list, name='role_list'),
    path('roles/delete/<int:pk>/', views.delete_role, name='delete_role'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
            serve, {'document_root': settings.MEDIA_ROOT,})
    ]

iplapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Team, Player, Match, IPLrole, PlayerStats
from .forms import TeamForm, PlayerFormEditAdd, MatchForm, PlayerStatsForm, MatchStatusForm, AssignRoleForm
from .forms import UserLoginForm, UserRegisterForm, PlayerForm, User, authenticate, login, logout
from django.utils import timezone
from django.db.models import Count, Sum
from django.db.models import Q, F
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.core.mail import send_mail
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect



# Create your views here.
###### Team Views ######

def team_list(request):
    teams = Team.objects.filter(active_status='active')
    return render(request, 'iplapp/team/team_list.html', {'teams': teams})


def team_detail(request, pk):
    cap = 'None';
    Won = 0;
    Lost = 0;
    Drawn = 0;
    try:
        team = get_object_or_404(Team, pk=pk)
        name = team.team_name
        run_list = PlayerStats.objects.filter(team=team).order_by('-created_date')[:10]
        matchesasguest = Match.objects.filter(guest_team=team.id)
        for match in matchesasguest:
            if match.guest_team_score > match.home_team_score:
                Won = Won + 1;
            if match.guest_team_score == match.home_team_score:
                Drawn = Drawn + 1
            if match.guest_team_score < match.home_team_score:
                Lost = Lost + 1

        matchesashome = Match.objects.filter(home_team=team.id)
        for match in matchesashome:
            if match.home_team_score > match.guest_team_score:
                Won = Won + 1;
            if match.guest_team_score == match.home_team_score:
                Drawn = Drawn + 1
            if match.home_team_score < match.guest_team_score:
                Lost = Lost + 1
        players = Player.objects.filter(team=team.id).filter(eligibility_status='eligible')
        for player in players:
            if player.team_role == 'captain':
                cap = player.first_name + " " + player.last_name
        totalrun = run_list.aggregate(TOTAL=Sum('run'))['TOTAL']
        return render(request, 'iplapp/team/team_detail.html', {'team': team,
                                                'run_list': run_list,
                                                'goals_count': totalrun,'players':players,
                                                'cap':cap,'Won':Won,'Lost':Lost,'Drawn':Drawn
                                                      })
    except Team.DoesNotExist:
        return render(request, 'iplapp/team/team_detail.html',
                      {'run_list': None,'cap':None,'players':None,'totalrun':0})

@login_required
def team_new(request):
    if request.method == "POST":
        #update
        form = TeamForm(request.POST)
        if form.is_valid():
            team = form.save(commit=False)
            team.created_date = timezone.now()
            team.save()
            teams = Team.objects.filter(created_date__lte=timezone.now())
            return render(request, 'iplapp/team/team_list.html', {'teams': teams})
    else:
        #edit
        form = TeamForm()
    return render(request, 'iplapp/team/team_edit.html', {'form': form})

@login_required
def team_edit(request, pk):
    team = get_object_or_404(Team, pk=pk)
    if request.method == "POST":
        form = TeamForm(request.POST, instance=team)
        if form.is_valid():
            team = form.save(commit=False)
            team.created_date = timezone.now()
            team.save()
            teams = Team.objects.filter(created_date__lte=timezone.now())
            return render(request, 'iplapp/team/team_list.html', {'teams': teams})
    else:
        #edit
        form = TeamForm(instance=team)
    return render(request, 'iplapp/team/team_edit.html', {'form': form})

@login_required
def team_delete(request, pk):
    team = get_object_or_404(Team, pk=pk)
    team.active_status = 'inactive'
    team.save()
    return redirect('iplapp:team_list')


## Player Views
def player_detail(request, pk):
    player = get_object_or_404(Player, pk=pk)
    team = player.team
    run_list = PlayerStats.objects.filter(player=player).order_by('-created_date')[:5]
    run_count = run_list.aggregate(TOTAL=Sum('run'))['TOTAL']
    return render(request, 'iplapp/player/player_detail.html', {'player': player,
                                                                'run_list': run_list,
                                                                'run_count': run_count,
                                                                'team': team})


def player_list(request):
    player_list = Player.objects.exclude(eligibility_status='ineligible')
    player_count = player_list.count()

    if(request.method == "GET"):
        qs = request.GET.get('playername')
        if qs:
            player_list = Player.objects.filter(Q(last_name__icontains=qs) |
                                                Q(first_name__icontains=qs)).exclude(eligibility_status='ineligible')
    return render(request, 'iplapp/player/player_list.html', {'player_list': player_list,
                                                              'player_count': player_count})

@login_required
def myteamplayer_list(request, pk):
    try:
        team = Team.objects.get(coach_id=pk)
        if team != None:
            myPlayer = Player.objects.filter(team=team.id)
            player_count = myPlayer.count()
        return render(request, 'iplapp/player//myteamplayer_list.html',
                      {'myplayer': myPlayer,
                       'player_count': player_count,
                       'coachid': pk})
    except Team.DoesNotExist:
        return render(request, 'iplapp/player/myteamplayer_list.html',
                      {'myplayer': None,
                       'player_count': 0,
                       'coachid': pk
                       })

@login_required
def player_new(request, coachid):
    if request.method == 'POST':
        form = PlayerFormEditAdd(request.POST)
        if form.is_valid():
            try:
                team = Team.objects.get(coach_id=coachid)
                if team != None:
                    player = form.save(commit=False)
                    player.created_date = timezone.now()
                    player.team = team
                    player.save()

                    players = Player.objects.filter(team=team.id)
                    player_count = players.count()
                return render(request, 'iplapp/player/myteamplayer_list.html',
                              {'myplayer': players,
                               'player_count': player_count,
                               'coachid': coachid})
            except Team.DoesNotExist:
                return render(request, 'iplapp/player/myteamplayer_list.html',
                              {'myplayer': None,
                               'player_count': 0,
                               'coachid': coachid
                               })
    else:
        #edit player
        form = PlayerFormEditAdd()
    return render(request, 'iplapp/player/player_edit.html', {'form': form})

@login_required
def player_edit(request, pk, coachid):
    player = get_object_or_404(Player, pk=pk)
    if request.method == "POST":
        #update
        form = PlayerFormEditAdd(request.POST, instance=player)
        if form.is_valid():
            team = Team.objects.get(coach_id=coachid)
            if team != None:
                player = form.save(commit=False)
                player.updated_date = timezone.now()
                player.team = team
                player.save()

                players = Player.objects.filter(team=team.id)
                player_count = players.count()
            #players = Player.objects.filter(created_date__lte=timezone.now())
            return render(request, 'iplapp/player/myteamplayer_list.html',
                          {'myplayer': players,
                           'player_count': player_count,
                           'coachid': coachid})
    else:
        # edit
        form = PlayerFormEditAdd(instance = player)
    return render(request, 'iplapp/player/player_edit.html', {'form': form})

@login_required
def player_delete(request, pk, coachid):
    player = get_object_or_404(Player, pk=pk)
    player.eligibility_status = 'ineligible'
    player.save()
    team = Team.objects.get(coach_id=coachid)
    if team != None:
        players = Player.objects.filter(team=team.id)
        player_count = players.count()
    return render(request, 'iplapp/player/myteamplayer_list.html',
                            {'myplayer': players,
                            'player_count': player_count,
                             'coachid': coachid})

##### Homepage Views
##############################
def home(request):
    matches_sch = Match.objects.filter(match_status='scheduled').order_by('match_day', 'match_start_time')[:3]
    matches_full = Match.objects.filter(match_status='full_time').order_by('-match_day', '-match_start_time')[:3]
    matches_live = Match.objects.filter(match_status='in_progress')
    team_live = Team.objects.filter(id=1)
    player_run_scorer = PlayerStats.objects.values('player__first_name', 'player__last_name',
                                                  'player__team__team_short_name', 'player__team__team_logo_url')\
                                                .annotate(total_run=Sum('run'))\
                                                .order_by('-total_run')[:5]
    teams = Team.objects.filter(created_date__lte=timezone.now()).order_by('-team_point')
    return render(request, 'home.html', {'matches_sch': matches_sch,

iplapp/templates/iplapp/match/match_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid padding">
<div class="row justify-content-center text-center">
    <div class="ipl-scorecard col-12 col-sm-12 col-md-10 col-lg-8">
        <div class="row text-left mt-2">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                <h6>{{match.match_day}} | {{match.field}} | Started at {{match.match_start_time}}</h6>
                <hr>
            </div>
        </div>
        <div class="row mx-1">
            <div class="col-4 col-sm-4 col-md-4 col-lg-4">
                <img src="{{ home_team.team_logo_url }}" class="img-fluid mx-auto mb-3" width="125">
                <h3>{{home_team.team_name}}</h3>
            </div>
            <div class="col-4 col-sm-4 col-md-4 col-lg-4 my-auto">
                <span class="ipl-livescore">
                    {{home_goals|length}} - {{guest_goals|length}}
                </span>
                <p class="ipl-livescore-sub">
                {% if match.match_status == 'scheduled' %}
                    Scheduled
                {% elif match.match_status == 'in_progress'%}
                    In Progress
                {% elif match.match_status == 'full_time'%}
                    Full Time
                {% elif match.match_status == 'cancelled'%}
                    Cancelled
                {% elif match.match_status == 'abandoned'%}
                    Abandoned
                {% else %}
                    Status - Not Available
                {% endif %}

                </p>
            </div>
            <div class="col-4 col-sm-4 col-md-4 col-lg-4">
                <img src="{{ guest_team.team_logo_url }}" class="img-fluid mx-auto mb-3" width="125">
                <h3>{{guest_team.team_name}}</h3>
            </div>
        </div>
        <div class="row mx-1">
            <div class="ipl-livescore-sub col-6 col-sm-6 col-md-6 col-lg-6 text-right">
                {% for goal in home_goals%}
                    <p>
                        {{goal.player}}&nbsp;{{goal.run}}'
                        <i class="fas fa-baseball-ball"></i>
                    </p>
                {% endfor%}
            </div>
            <div class="ipl-livescore-sub col-6 col-sm-6 col-md-6 col-lg-6 text-left">
                {% for goal in guest_goals%}
                    <p>
                        <i class="fas fa-baseball-ball"></i>&nbsp;
                        {{goal.run}}'&nbsp;{{goal.player}}
                    </p>
                {% endfor%}
            </div>
        </div>
        {% if user.is_authenticated and user.groups.all and user.groups.all.0.name == "Scorer" and match.match_referee == user or request.user.is_superuser%}
        {% if match.match_status == 'scheduled' or match.match_status == 'in_progress' or request.user.is_superuser%}
            <hr>
            <div class="row mx-1">
                <div class="ipl-livescore-sub col-6 col-sm-6 col-md-6 col-lg-6 text-right">
                    <form method="POST" id="homeGoalForm" class="goal-form">
                        {{home_goal_form.as_p}}
                        {%csrf_token%}
                        <button type="submit" name="home_goal_submit" class="save btn btn-default">Add Score</button>
                    </form>
                </div>
                <div class="ipl-livescore-sub col-6 col-sm-6 col-md-6 col-lg-6 text-left">
                    <form method="POST" id="guestGoalForm" class="goal-form">
                        {{guest_goal_form.as_p}}
                        {%csrf_token%}
                        <button type="submit" name="guest_goal_submit" class="save btn btn-default">Add Goal</button>
                    </form>
                </div>
            </div>
            <hr>
            <div class="row mx-1">
                <div class="ipl-livescore-sub col-12 col-sm-12 col-md-12 col-lg-12 text-left">
                    <form method="POST" id="matchStatusForm" class="goal-form">
                        {{match_status_form.as_p}}
                        {%csrf_token%}
                        <button type="submit" name="update_match_status" class="save btn btn-default">Update Match Status</button>
                    </form>
                </div>
            </div>
        {% endif %}
        {% endif %}
    </div>
</div>
</div>
{% endblock %}

iplapp/templates/iplapp/match/match_edit.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid padding">
<div class="row padding">
<div class="col-md-6">
    <h1>Add/Edit Match</h1>
    <form method="POST">
        {{form.as_p}}
        {%csrf_token%}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
</div>
</div>
</div>
{% endblock %}

iplapp/templates/iplapp/match/match_list.html
{% extends "match_list_base.html" %}
{% load static %}

{% block match_list_content %}
<div class="container-fluid padding">
<div class="row padding">
<div class="col-md-12">
    <div class="table-responsive">
        <table class="table table-sm table-hover">
            <tbody>
                {% for match in match_list %}
                <tr>
                    <td>
                        <a class="fa-icons" href="{% url 'iplapp:match_detail' pk=match.pk %}">
                            <i class="fa fa-eye"></i>
                        </a>
                        {% if user.is_authenticated and request.user.is_superuser or user.groups.all and user.groups.all.0.name == "Admin" %}
                        &nbsp
                        <a class="fa-icons" href="{% url 'iplapp:match_edit' pk=match.pk %}">
                            <i class="fa fa-edit"></i>
                        </a>
                        &nbsp
                        <a class="fa-icons" href="{% url 'iplapp:match_delete' pk=match.pk %}" onclick="return confirm('Are you sure you want to Delete?')">
                            <i class="fa fa-trash"></i>
                        </a>
                        {% endif %}
                    </td>
                    <td style="text-align: right">
                        <img src="{{ team.team_logo_url }}" width="20">
                        {{ match.home_team}}
                    </td>
                    <td style="text-align: center">
                        <strong>({{match.home_team_score}} - {{match.guest_team_score}})</strong>
                    </td>
                    <td>{{ match.guest_team }}</td>
                    <td>{{ match.match_day }}, {{ match.match_start_time }}</td>
                    <td>
                        {% if match.match_status == 'scheduled' %}
                            Scheduled
                        {% elif match.match_status == 'in_progress'%}
                            In Progress
                        {% elif match.match_status == 'full_time'%}
                            Full Time
                        {% elif match.match_status == 'cancelled'%}
                            Cancelled
                        {% elif match.match_status == 'abandoned'%}
                            Abandoned
                        {% else %}
                            Status - Not Available
                        {% endif %}
                    </td>
                    <td>{{ match.field }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
</div>
</div>
{% endblock%}

iplapp/templates/iplapp/match/referee_dashboard.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid padding">
<div class="row padding">
<div class="col-md-12">
    <div class="table-responsive">
        <table class="table table-sm table-hover">
            <tbody>
                {% for match in match_list %}
                <tr>
                    <td>
                        <a class="fa-icons" href="{% url 'iplapp:match_detail' pk=match.pk %}">
                            <i class="fa fa-eye"></i>
                        </a>
                    </td>
                    <td style="text-align: right">
                        <img src="{{ team.team_logo.url }}" width="20">
                        {{ match.home_team}}
                    </td>
                    <td style="text-align: center">
                        <strong>({{match.home_team_score}} - {{match.guest_team_score}})</strong>
                    </td>
                    <td>{{ match.guest_team }}</td>
                    <td>{{ match.match_day }}, {{ match.match_start_time }}</td>
                    <td>
                        {% if match.match_status == 'scheduled' %}
                            Scheduled
                        {% elif match.match_status == 'in_progress'%}
                            In Progress
                        {% elif match.match_status == 'full_time'%}
                            Full Time
                        {% elif match.match_status == 'cancelled'%}
                            Cancelled
                        {% elif match.match_status == 'abandoned'%}
                            Abandoned
                        {% else %}
                            Status - Not Available
                        {% endif %}
                    </td>
                    <td>{{ match.field }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
</div>
</div>

{% endblock %}